name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Backend install & test
      - name: Install Backend dependencies
        working-directory: ./Backend
        run: npm install

      - name: Run Backend tests
        working-directory: ./Backend
        run: npm test

      # Frontend install & build
      - name: Install Frontend dependencies
        working-directory: ./Frontend
        run: npm install

      - name: Build Frontend (Next.js)
        working-directory: ./Frontend
        run: npm run build

      - name: Run Frontend tests (si tu as des tests)
        working-directory: ./Frontend
        run: npm test
